/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.ComicReader;
import jaco.mp3.player.MP3Player;
import java.io.File;
import javax.swing.ImageIcon;

/**
 *
 * @author Luis Araujo
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        setSize(618, 402);
        fundo.setIcon(new ImageIcon("src\\imagens\\dance.jpg"));
        fundo.setOpaque(true);
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     public   String musica = "C:\\Users\\Luis Araujo\\Desktop\\ComicReader\\dontmean.mp3";
     MP3Player mp3player = new MP3Player(new File(musica));
    
     
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        COMICS = new javax.swing.JButton();
        INFO = new javax.swing.JButton();
        PLAY = new javax.swing.JButton();
        PAUSE = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        books = new javax.swing.JLabel();
        books2 = new javax.swing.JLabel();
        explosion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setResizable(false);
        getContentPane().setLayout(null);

        COMICS.setText("COMICS");
        COMICS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        COMICS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMICSActionPerformed(evt);
            }
        });
        getContentPane().add(COMICS);
        COMICS.setBounds(263, 240, 100, 23);

        INFO.setText("INFO");
        INFO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(INFO);
        INFO.setBounds(260, 300, 100, 23);

        PLAY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/playbutton.png"))); // NOI18N
        PLAY.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PLAY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PLAYMouseClicked(evt);
            }
        });
        PLAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLAYActionPerformed(evt);
            }
        });
        getContentPane().add(PLAY);
        PLAY.setBounds(490, 10, 30, 29);

        PAUSE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pausebutton.png"))); // NOI18N
        PAUSE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PAUSE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PAUSEMouseClicked(evt);
            }
        });
        PAUSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PAUSEActionPerformed(evt);
            }
        });
        getContentPane().add(PAUSE);
        PAUSE.setBounds(530, 10, 30, 29);
        getContentPane().add(fundo);
        fundo.setBounds(0, 0, 630, 400);

        titulo.setBackground(new java.awt.Color(0, 51, 255));
        titulo.setFont(new java.awt.Font("Yu Gothic", 3, 36)); // NOI18N
        titulo.setText("ComicReader");
        titulo.setOpaque(true);
        getContentPane().add(titulo);
        titulo.setBounds(190, 80, 250, 50);

        books.setText("jLabel1");
        getContentPane().add(books);
        books.setBounds(10, 210, 100, 190);

        books2.setText("jLabel1");
        getContentPane().add(books2);
        books2.setBounds(530, 230, 80, 150);

        explosion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/6-67945_comic-book-bubble-transparent.png"))); // NOI18N
        explosion.setText("jLabel1");
        explosion.setOpaque(true);
        getContentPane().add(explosion);
        explosion.setBounds(190, 10, 230, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void COMICSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMICSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COMICSActionPerformed

    private void PLAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLAYActionPerformed
        // TODO add your handling code here:
        ComicReader.PlayMP3();
    }//GEN-LAST:event_PLAYActionPerformed

    private void PLAYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLAYMouseClicked
        // TODO add your handling code here:
       ComicReader.PlayMP3();
    }//GEN-LAST:event_PLAYMouseClicked

    private void PAUSEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PAUSEMouseClicked
        // TODO add your handling code here:
        ComicReader.PauseMP3();
    }//GEN-LAST:event_PAUSEMouseClicked

    private void PAUSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PAUSEActionPerformed
        // TODO add your handling code here:
         ComicReader.PauseMP3();
    }//GEN-LAST:event_PAUSEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton COMICS;
    private javax.swing.JButton INFO;
    private javax.swing.JButton PAUSE;
    private javax.swing.JButton PLAY;
    private javax.swing.JLabel books;
    private javax.swing.JLabel books2;
    private javax.swing.JLabel explosion;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
